# YAML file format
# ## SNAKEMAKE PARAMETERS - ADAPT HERE
snakefile: scripts/OR_script.snake
cores: 1
use-conda: True
use-singularity: True
singularity-args: ""
rerun-incomplete: True
restart-times: 1
configfile: scripts/parameters.yaml
