# YAML file format
## SCRIPT PARAMETERS - ADAPT HERE

# Directory with input fastq files and reference genome
DATADIR: "/home/courcellem/scratch/OR_SCRIPT/data/"

# Reference genome file
refgen: "ref/NC_005283.1.fasta"

